### ISSUE TITLE
Extend EBS-Snapper to do cross-region snapshot copy

### ISSUE THREAD

**Issue by auroan** [rackerlabs/ebs_snapper#15]
Would it be possible to have the ebs_snapper perform a cross region copy of a snapshot when is has completed against a volume.

This would provide some form of initial region level DR capability for customers.

**Comment by martinb3** [comment]
Yes, I think this would be possible to implement; it would have to be something that runs _after_ an initial snapshot completes, though, so not synchronous. However, since I see EBS snapshots as a stopgap, I'd probably push folks to use S3 or RDS for the data, where AWS intends for enabling more DR capability.

**Comment by mlattanzi** [comment]
I have a build right now with the customer requesting cross-region replication of snapshots so this would definitely be a nice feature to have!

**Comment by lindseyanderson** [comment]
Have to agree now as well, we have a few large, enterprise customers now requesting this feature.

**Comment by martinb3** [comment]
This was completed today in #38. We should be doing a release shortly.
